[package]
name = "snapatac2-core"
version = "0.1.0"
edition = "2021"
authors = ["Kai Zhang <kai@kzhang.org>"]
description = "Rust APIs"
license = "MIT"
readme = "README.md"
repository = "https://github.com/"
homepage = "https://github.com/"
keywords = ["single-cell", "biology"]

[dependencies]
flate2 = "1.0"
itertools = "0.8"
bed-utils = { git = "https://github.com/kaizhang/bed-utils.git", rev = "5649e8e82af36bb1e35807384fb108c0591a098a" }
hdf5 = "0.8.1"
ndarray = "0.15.4"
num = "0.4.0"
noodles-gff = "0.5.0"
rayon = "1.5.1"
nalgebra-sparse = "0.6.0"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "benchmark"
harness = false
